'use client';

import React from 'react';
import HeroSection from '@/components/HeroSection';
import ServicesShowcase from '@/components/ServicesShowcase';
import PortfolioGallery from '@/components/PortfolioGallery';
import BookingSystem from '@/components/BookingSystem';
import ExpertiseSection from '@/components/ExpertiseSection';
import ContactFooter from '@/components/ContactFooter';

export default function HomePage() {
  return (
    <>
      <main className="flex-1 container mx-auto px-4 py-8">
        {/* Components generated by the builder will be added here */}
      
        <HeroSection />
        <ServicesShowcase />
        <PortfolioGallery />
        <BookingSystem />
        <ExpertiseSection />
        <ContactFooter />
      </main>
    </>
  );
}